package luau

import (
	"regexp"
	"strings"
	"unicode"
)

var generatedRes = []*regexp.Regexp{
	regexp.MustCompile(`(?i)^(?:v|u|p|a|r|l|var|arg|args|upv|upval|upvalue|param|slot|reg|loc|local|val|tbl|func|fn)_?\d+$`),
	regexp.MustCompile(`^l_[A-Za-z_][A-Za-z0-9_]*_\d+$`), // l_Players_0 (Medal/Konstant)
	regexp.MustCompile(`^[A-Z]\d+_\d+$`),                 // L0_1 (unluac style)
	regexp.MustCompile(`^(?:[vupal]_)+\d+$`), // v_u_1 (Medal upvalues)
	regexp.MustCompile(`^_\d+$`),
}

var lNameRe = regexp.MustCompile(`^l_([A-Za-z_][A-Za-z0-9_]*)_\d+$`)

// LooksGenerated reports whether name looks machine-generated by a decompiler.
func LooksGenerated(name string) bool {
	for _, re := range generatedRes {
		if re.MatchString(name) {
			return true
		}
	}
	return false
}

// eventParams names the parameters of common Roblox event callbacks.
var eventParams = map[string][]string{
	"Touched": {"hit"}, "TouchEnded": {"hit"},
	"PlayerAdded": {"player"}, "PlayerRemoving": {"player"},
	"CharacterAdded": {"character"}, "CharacterRemoving": {"character"}, "CharacterAppearanceLoaded": {"character"},
	"ChildAdded": {"child"}, "ChildRemoved": {"child"},
	"DescendantAdded": {"descendant"}, "DescendantRemoving": {"descendant"},
	"InputBegan": {"input", "gameProcessedEvent"}, "InputEnded": {"input", "gameProcessedEvent"},
	"InputChanged": {"input", "gameProcessedEvent"},
	"Heartbeat":    {"deltaTime"}, "RenderStepped": {"deltaTime"}, "Stepped": {"runTime", "deltaTime"},
	"PreSimulation": {"deltaTime"}, "PostSimulation": {"deltaTime"}, "PreRender": {"deltaTime"}, "PreAnimation": {"deltaTime"},
	"OnServerEvent": {"player"}, "OnServerInvoke": {"player"},
	"HealthChanged": {"health"}, "FocusLost": {"enterPressed", "inputThatCausedFocusLoss"},
	"Activated": {"inputObject", "clickCount"}, "Triggered": {"player"}, "MouseClick": {"player"},
	"TriggerEnded": {"player"}, "PromptTriggered": {"prompt", "player"}, "PromptButtonHoldBegan": {"prompt", "player"},
	"Chatted": {"message", "recipient"}, "AncestryChanged": {"child", "parent"},
	"AttributeChanged": {"attribute"}, "Completed": {"playbackState"}, "KeyframeReached": {"keyframeName"},
	"MoveToFinished": {"reached"}, "StateChanged": {"oldState", "newState"}, "Running": {"speed"},
	"MouseEnter": {"x", "y"}, "MouseLeave": {"x", "y"}, "MouseMoved": {"x", "y"},
	"PlayerMembershipChanged": {"player"}, "PromptPurchaseFinished": {"player", "assetId", "isPurchased"},
	"PromptProductPurchaseFinished":  {"userId", "productId", "isPurchased"},
	"PromptGamePassPurchaseFinished": {"player", "gamePassId", "wasPurchased"},
	"Died":                           {}, "Changed": {}, "Event": {}, "OnClientEvent": {}, "Equipped": {"mouse"},
}

// constructors maps Type.new(...) style calls to a variable name.
var constructors = map[string]string{
	"CFrame": "cframe", "Vector3": "vector", "Vector2": "vector2", "Color3": "color", "UDim2": "udim2",
	"UDim": "udim", "TweenInfo": "tweenInfo", "RaycastParams": "raycastParams", "OverlapParams": "overlapParams",
	"NumberSequence": "numberSequence", "ColorSequence": "colorSequence", "NumberRange": "numberRange",
	"Random": "rng", "Ray": "ray", "BrickColor": "brickColor", "Region3": "region", "Rect": "rect",
	"DateTime": "dateTime", "PhysicalProperties": "physicalProperties", "Font": "font",
}

var fieldNames = map[string]string{
	"CurrentCamera": "camera", "LocalPlayer": "localPlayer", "Character": "character", "Humanoid": "humanoid",
	"HumanoidRootPart": "rootPart", "PrimaryPart": "primaryPart", "PlayerGui": "playerGui", "Backpack": "backpack",
	"Parent": "parent", "Value": "value", "Name": "name", "Position": "position", "CFrame": "cframe",
	"Size": "size", "Magnitude": "magnitude", "Unit": "direction", "LookVector": "lookVector",
	"Health": "health", "MaxHealth": "maxHealth", "WalkSpeed": "walkSpeed", "Animator": "animator",
	"UserId": "userId", "Team": "team", "leaderstats": "leaderstats", "Text": "text",
}

var childFinders = map[string]bool{
	"WaitForChild": true, "FindFirstChild": true, "FindFirstChildOfClass": true, "FindFirstChildWhichIsA": true,
	"FindFirstAncestor": true, "FindFirstAncestorOfClass": true, "FindFirstAncestorWhichIsA": true,
	"FindFirstDescendant": true,
}

var methodNames = map[string]string{
	"GetChildren": "children", "GetDescendants": "descendants", "GetPlayers": "players", "GetMouse": "mouse",
	"LoadAnimation": "animationTrack", "Raycast": "raycastResult", "GetPlayerFromCharacter": "player",
	"InvokeServer": "response", "InvokeClient": "response", "GetTagged": "taggedInstances",
	"GetPartBoundsInBox": "parts", "GetPartBoundsInRadius": "parts", "GetPartsInPart": "parts",
	"GetBoundingBox": "boundingBox", "GetPivot": "pivot", "GetAsync": "data", "GetDataStore": "dataStore",
	"GetOrderedDataStore": "orderedDataStore", "JSONDecode": "decoded", "JSONEncode": "json",
	"GenerateGUID": "guid", "GetUserIdFromNameAsync": "userId", "GetNameFromUserIdAsync": "username",
	"GetMarkerReachedSignal": "markerSignal", "GetPlayingAnimationTracks": "animationTracks",
	"GetState": "humanoidState", "GetAttributes": "attributes", "GetFullName": "fullName",
	"ViewportPointToRay": "ray", "ScreenPointToRay": "ray", "WorldToViewportPoint": "screenPoint",
	"WorldToScreenPoint": "screenPoint", "GetMouseLocation": "mouseLocation", "IsKeyDown": "isKeyDown",
	"GetProductInfo": "productInfo", "UserOwnsGamePassAsync": "ownsGamePass", "Clone": "clone",
}

var plainCalls = map[string]string{
	"tick": "now", "time": "now", "os.clock": "startClock", "os.time": "timestamp", "workspace.GetServerTimeNow": "serverTime",
}

// SuggestNames infers descriptive names for decompiler-generated variables
// from how they are initialised and used. It never touches names that already
// look human-written. The result maps binding IDs to suggested names.
func (f *File) SuggestNames() map[int]string {
	out := map[int]string{}
	nameOf := func(id int) string {
		if n, ok := out[id]; ok {
			return n
		}
		return f.Bindings[id].Name
	}
	for _, b := range f.Bindings {
		if !b.Renamable() || !LooksGenerated(b.Name) {
			continue
		}
		var n string
		if m := lNameRe.FindStringSubmatch(b.Name); m != nil {
			n = m[1]
		}
		if n == "" {
			switch b.Kind {
			case BindLocal:
				if b.Init[0] >= 0 {
					n = f.inferExpr(b.Init[0], b.Init[1], nameOf)
				}
			case BindParam:
				if ps, ok := eventParams[b.Event]; ok && b.ParamIndex < len(ps) {
					n = ps[b.ParamIndex]
				}
			case BindForNum:
				n = "i"
			case BindFor:
				n = f.inferIter(b, nameOf)
			}
		}
		if n != "" && ValidName(n) && n != b.Name {
			out[b.ID] = n
		}
	}
	return out
}

type segment struct {
	field  string // .Field
	method string // :Method(...)
	arg    string // first string argument of a call, unquoted
	call   bool
}

// chain parses toks[s:e] as a pure suffixed expression (a.b:c("x").d).
// It returns the root token text and the suffix segments, or ok=false when
// the expression is anything else (arithmetic, literals, ...).
func (f *File) chain(s, e int) (root string, rootTok int, segs []segment, ok bool) {
	if s >= e || f.Toks[s].Kind != Name {
		return "", -1, nil, false
	}
	root, rootTok = f.Toks[s].Text, s
	i := s + 1
	for i < e {
		t := f.Toks[i]
		switch {
		case t.Kind == Op && t.Text == "." && i+1 < e && f.Toks[i+1].Kind == Name:
			segs = append(segs, segment{field: f.Toks[i+1].Text})
			i += 2
		case t.Kind == Op && t.Text == ":" && i+1 < e && f.Toks[i+1].Kind == Name:
			seg := segment{method: f.Toks[i+1].Text, call: true}
			j, arg, good := f.skipArgs(i+2, e)
			if !good {
				return "", -1, nil, false
			}
			seg.arg = arg
			segs = append(segs, seg)
			i = j
		case t.Kind == Op && t.Text == "(", t.Kind == String:
			j, arg, good := f.skipArgs(i, e)
			if !good {
				return "", -1, nil, false
			}
			segs = append(segs, segment{call: true, arg: arg})
			i = j
		case t.Kind == Op && t.Text == "[":
			depth := 0
			for ; i < e; i++ {
				if f.Toks[i].Kind == Op && f.Toks[i].Text == "[" {
					depth++
				} else if f.Toks[i].Kind == Op && f.Toks[i].Text == "]" {
					depth--
					if depth == 0 {
						break
					}
				}
			}
			i++
			segs = append(segs, segment{})
		default:
			return "", -1, nil, false
		}
	}
	return root, rootTok, segs, true
}

// skipArgs skips call arguments starting at i and returns the index after
// them plus the first argument when it is a plain string literal.
func (f *File) skipArgs(i, e int) (int, string, bool) {
	if i >= e {
		return i, "", false
	}
	t := f.Toks[i]
	if t.Kind == String {
		return i + 1, unquote(t.Text), true
	}
	if t.Kind != Op || (t.Text != "(" && t.Text != "{") {
		return i, "", false
	}
	open, close := t.Text, ")"
	if open == "{" {
		close = "}"
	}
	arg := ""
	if open == "(" && i+1 < e && f.Toks[i+1].Kind == String {
		arg = unquote(f.Toks[i+1].Text)
	}
	depth := 0
	for ; i < e; i++ {
		tt := f.Toks[i]
		if tt.Kind != Op {
			continue
		}
		switch tt.Text {
		case "(", "{", "[":
			depth++
		case ")", "}", "]":
			depth--
			if depth == 0 && tt.Text == close {
				return i + 1, arg, true
			}
		}
	}
	return i, "", false
}

func unquote(s string) string {
	if len(s) >= 2 && (s[0] == '"' || s[0] == '\'' || s[0] == '`') {
		return s[1 : len(s)-1]
	}
	if strings.HasPrefix(s, "[") {
		if i := strings.Index(s[1:], "["); i >= 0 {
			body := s[i+2:]
			if j := strings.LastIndex(body, "]"); j >= 0 {
				body = body[:j]
				return strings.TrimRight(body, "=]")
			}
		}
	}
	return s
}

func (f *File) inferExpr(s, e int, nameOf func(int) string) string {
	if s >= e {
		return ""
	}
	root, rootTok, segs, ok := f.chain(s, e)
	if !ok {
		return ""
	}
	// require(...) -> module name
	if root == "require" && f.Resolve[rootTok] == Global && len(segs) == 1 && segs[0].call {
		return pascal(f.lastNameIn(s+1, e))
	}
	if len(segs) == 0 {
		return "" // plain alias of another variable
	}
	last := segs[len(segs)-1]
	prevName := func() string {
		for i := len(segs) - 2; i >= 0; i-- {
			if segs[i].field != "" {
				return segs[i].field
			}
			if segs[i].method != "" && childFinders[segs[i].method] && segs[i].arg != "" {
				return segs[i].arg
			}
		}
		if f.Resolve[rootTok] >= 0 {
			if n := nameOf(f.Resolve[rootTok]); !LooksGenerated(n) {
				return n
			}
		}
		return ""
	}
	if f.Resolve[rootTok] == Global {
		if len(segs) == 2 && segs[0].field == "new" && segs[1].call && root == "Instance" && last.arg != "" {
			return camel(last.arg)
		}
		if len(segs) == 2 && segs[1].call && segs[0].field != "" {
			if n, ok := constructors[root]; ok {
				return n
			}
			if n, ok := plainCalls[root+"."+segs[0].field]; ok {
				return n
			}
		}
		if len(segs) == 1 && last.call && last.method == "" {
			return plainCalls[root]
		}
	}
	switch {
	case last.method == "GetService" && last.arg != "":
		return pascal(last.arg)
	case last.method != "" && childFinders[last.method] && last.arg != "":
		return camel(last.arg)
	case last.method == "Clone":
		if p := prevName(); p != "" {
			return camel(p) + "Clone"
		}
		return "clone"
	case connectMethods[last.method]:
		if p := prevName(); p != "" {
			return camel(p) + "Connection"
		}
		return "connection"
	case last.method == "Wait":
		if p := prevName(); p != "" {
			if ps := eventParams[p]; len(ps) > 0 {
				return ps[0]
			}
		}
	case last.method == "Create" && len(segs) >= 1:
		if strings.Contains(strings.ToLower(f.Toks[rootTok].Text+prevName()), "tween") {
			return "tween"
		}
	case last.method == "GetAttribute" && last.arg != "":
		return camel(last.arg)
	case last.method == "GetPropertyChangedSignal" && last.arg != "":
		return camel(last.arg) + "Changed"
	case last.method != "":
		return methodNames[last.method]
	case last.field != "":
		if n, ok := fieldNames[last.field]; ok {
			return n
		}
		if len(last.field) >= 2 {
			return camel(last.field)
		}
	}
	return ""
}

// lastNameIn returns the last string literal or field name inside toks[s:e],
// used to name required modules.
func (f *File) lastNameIn(s, e int) string {
	for i := e - 1; i >= s; i-- {
		t := f.Toks[i]
		if t.Kind == String {
			v := unquote(t.Text)
			if j := strings.LastIndexAny(v, "/."); j >= 0 {
				v = v[j+1:]
			}
			return v
		}
		if t.Kind == Name && i > s && f.Toks[i-1].Kind == Op && f.Toks[i-1].Text == "." {
			return t.Text
		}
	}
	return ""
}

func (f *File) inferIter(b *Binding, nameOf func(int) string) string {
	s, e := b.Iter[0], b.Iter[1]
	if s < 0 {
		return ""
	}
	kind := "" // pairs | ipairs | ""
	cs, ce := s, e
	if f.Toks[s].Kind == Name && (f.Toks[s].Text == "pairs" || f.Toks[s].Text == "ipairs") && f.Resolve[s] == Global &&
		s+1 < e && f.Toks[s+1].Text == "(" && f.Toks[e-1].Text == ")" {
		kind, cs, ce = f.Toks[s].Text, s+2, e-1
	} else if f.Toks[s].Kind == Name && f.Toks[s].Text == "next" && s+1 < e && f.Toks[s+1].Text == "," {
		kind, cs = "pairs", s+2
	}
	container := ""
	arrayLike := kind == "ipairs"
	if root, rootTok, segs, ok := f.chain(cs, ce); ok {
		if len(segs) == 0 {
			if id := f.Resolve[rootTok]; id >= 0 {
				container = nameOf(id)
			} else {
				container = root
			}
		} else if last := segs[len(segs)-1]; last.method != "" {
			container = methodNames[last.method]
			arrayLike = true
		} else if last.field != "" {
			container = last.field
		}
	}
	if b.IterPos == 0 {
		if arrayLike {
			return "index"
		}
		if kind != "" {
			return "key"
		}
		return ""
	}
	if b.IterPos == 1 {
		if container != "" && !LooksGenerated(container) {
			if s := singular(camel(container)); s != "" {
				return s
			}
		}
		if kind != "" || arrayLike {
			return "value"
		}
	}
	return ""
}

func singular(s string) string {
	ls := strings.ToLower(s)
	switch {
	case ls == "children":
		return s[:len(s)-3]
	case strings.HasSuffix(ls, "ies") && len(s) > 4:
		return s[:len(s)-3] + "y"
	case strings.HasSuffix(ls, "ses") || strings.HasSuffix(ls, "xes"):
		return s[:len(s)-2]
	case strings.HasSuffix(ls, "s") && !strings.HasSuffix(ls, "ss") && len(s) > 3:
		return s[:len(s)-1]
	}
	return ""
}

// words splits an arbitrary string ("Remote Events", "kill_brick") into words.
func words(s string) []string {
	return strings.FieldsFunc(s, func(r rune) bool {
		return !(unicode.IsLetter(r) || unicode.IsDigit(r)) || r > unicode.MaxASCII
	})
}

func joinIdent(s string, upperFirst bool) string {
	ws := words(s)
	var sb strings.Builder
	for i, w := range ws {
		w = strings.Trim(w, "_")
		if w == "" {
			continue
		}
		if i == 0 || sb.Len() == 0 {
			if upperFirst {
				w = strings.ToUpper(w[:1]) + w[1:]
			} else if !isAllUpper(w) || len(w) == 1 {
				w = strings.ToLower(w[:1]) + w[1:]
			} else {
				w = strings.ToLower(w)
			}
		} else {
			w = strings.ToUpper(w[:1]) + w[1:]
		}
		sb.WriteString(w)
	}
	out := sb.String()
	if out == "" {
		return ""
	}
	if isDigit(out[0]) {
		out = "_" + out
	}
	return out
}

func isAllUpper(s string) bool {
	for _, r := range s {
		if unicode.IsLower(r) {
			return false
		}
	}
	return true
}

func camel(s string) string  { return joinIdent(s, false) }
func pascal(s string) string { return joinIdent(s, true) }

// ToIdent turns a suggested name into a valid identifier: valid names are
// returned unchanged, anything else ("player gui", "kill-brick") is camelCased.
func ToIdent(s string) string {
	s = strings.TrimSpace(s)
	if identRe.MatchString(s) {
		return s
	}
	return camel(s)
}
